name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'

jobs:
  build:
    name: Build modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # THIS STEP RECREATES THE MISSING .JKS FILE
      - name: Prepare signing key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > signingkey.jks

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build extensions
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: chmod +x ./gradlew && ./gradlew assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: "extension-apks"
          path: "**/*.apk"
